# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 421d30730f7b1532bb4ac0ebd8c557a9743ba801106e7b883587b2b009d72cad8d57233c49c7cf4b3e57cffa5ff43e3189c8c08a1a866565f850e86e309472a4

test:
  secret_key_base: c7bff47259f6a561e4e06e559f7ed5a80ac0f664637908aeafbf324c3c44fdca49dfeb626b9eac15a0b5ea3008fb13a50411b60373ab0347cd956056041ff5f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
